[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_flat_30_cccccc_40x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_flat_50_5c5c5c_40x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_glass_40_ffc73d_1x400.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_highlight-hard_20_0972a5_1x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_highlight-soft_33_003147_1x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_highlight-soft_35_222222_1x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_highlight-soft_44_444444_1x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_highlight-soft_80_eeeeee_1x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-bg_loop_25_000000_21x21.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-icons_222222_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-icons_a83300_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-icons_cccccc_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.images.ui-icons_ffffff_256x240.png", "image/png")]

[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.css.ci.default.ci.default.css", "text/css")]

[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.js.libs.CIAPI.min.js", "application/x-javascript")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.js.libs.CIAPI.debug.js", "application/x-javascript")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.js.libs.CIAPI.widget.min.js", "application/x-javascript")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.js.libs.CIAPI.widget.debug.js", "application/x-javascript")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.js.CIAPI.Authentication.min.js", "application/x-javascript")]
[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.js.CIAPI.Authentication.debug.js", "application/x-javascript")]

[assembly: System.Web.UI.WebResource("CIAPI.AspNet.Controls.Authentication.js.CIAPI.amplify.requests.mock.js", "application/x-javascript")]
